### PR TITLE
Fix session creation for auto-login when resetting password

### LINKED ISSUE #164: autoLogin does not create session for change password flow
This is not creating the password-based token session:

https://github.com/stormpath/express-stormpath/blob/master/lib/controllers/change-password.js#L71

### PR DESCRIPTION
**Pull request by typerandom**
Fixes so that a session cookie is created when `web.changePassword.autoLogin` is enabled and you're resetting the password for an account.

#### How to verify

1. Create a new application using [this gist](https://gist.github.com/typerandom/419d4346aa5e01ade26e50251768cbc9).
2. Start the application.
3. Navigate to the forgot password page (http://localhost:3000/forgot) and reset the password for one of your accounts.
4. Click the reset password link in the email you received and change the password for your account.
5. You should be redirected to `/` and logged in.

Fixes #164

### CODE REVIEW

**Comment by robertjd** [comment]
I've verified that this PR fixes the reported problem, however I'm also noticing that the pre/post handlers are not being run for this case.  Can we refactor the code to handle those cases as well?  I know it may touch many files, but it seems like we can consolidate a lot of this.

**Comment by typerandom** [comment]
@robertjd The latest changes are now pushed.

File: test/handlers/test-pre-login-handler.js [hunk 1]
```diff
@@ -145,33 +148,29 @@ describe('Pre-Login Handler', function () {
...
+                .set('Accept', 'application/json')
+                .type('json')
+                .send(usernamePasswordBody)
+                .expect(200)
+                .end(function (err) {
+                  if (err) {
+                    return done(err);
+                  }
+
+                  var preLoginHandlerFormData = fixture.preLoginHandlerFormData;
```
Comment (robertjd) [inline test/handlers/test-pre-login-handler.js]: The intention of this test case is to assert that the developer can end the response inside of their preLoginHandler, and that their response will be the final one.

These modifications don't assert that code path anymore, because the `preLoginHandlerInterceptResponseTestFixture` has been modified to always call `next()`, so we aren't testing a custom response by the developer anymore.  This test should be reverted back to it's original intent.

**Comment by robertjd** [comment]
Thanks @typerandom !  This looks great and I've verified that it solves the original issue.

I do have one issue with a test change, please see my inline comments.  In sum: we need to make sure that we have a test case that asserts the developer's ability to end the response from inside their handler, preventing the rest of the next() handlers from running.  I'd like to address this test issue before we merge.

File: test/handlers/test-pre-login-handler.js (hunk 1 above)
Comment (typerandom) [inline test/handlers/test-pre-login-handler.js]: Okay, I see. I'll fix that!

**Comment by typerandom** [comment]
@robertjd I saw your comment and I'll fix the code/test before we continue.

**Comment by typerandom** [comment]
@robertjd This is fixed now.
